services:
  app:
    image: node:16
    depends_on:
      - postgres
    command: sh -c "npm install && npm run dev"
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PORT=5000
      - NODE_ENV=development
      - DATABASE_NAME=blog_app
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgrespw
      - DATABASE_HOST=postgres
      - DATABASE_DIALECT=postgres
      - JWT_SECRET=super ultra mega secret key
  postgres:
    image: postgres
    volumes:
      - blog_app-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=blog_app

volumes:
  blog_app-data:
